server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/wish?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: rhqemddl12
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

logging:
  level:
    org.hibernate.SQL: debug
